language: csharp
solution: Bearded.Audio.sln

mono:
 - alpha

install:
  - nuget restore Bearded.Audio.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Bearded.Audio.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/bin/Release/Bearded.Audio.Tests.dll
