version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

nuget:
  project_feed: true

before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'
  name: Nuget Packages
